version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\rayyildiz\twitter-streaming

environment:
    GOPATH: c:\gopath
    GOVERSION: 1.11.2

init:
    - git config --global core.autocrlf input

install:
    - choco install golang --version %GOVERSION% -y
    - set Path=c:\go\bin;c:\gopath\bin;%Path%
    - go env

build: false
deploy: false

test_script:
    - go build github.com/rayyildiz/twitter-streaming

